/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testexamgenerator.window;

import com.hp.hpl.jena.util.FileUtils;
import java.io.File;
import java.io.FilenameFilter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import testexamgenerator.dto.Unit;
import testexamgenerator.logic.BusinessLogic;
import testexamgenerator.logic.exception.NotEnoughQuestionsException;

/**
 *
 * @author pablo
 */
public class JDialogGenerateExam extends javax.swing.JDialog {

    /**
     * Creates new form JDialogNew
     */
    public JDialogGenerateExam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
        List<Unit> listUnit = BusinessLogic.getUnitList();
        DefaultListModel dlm = new DefaultListModel();
        for (Unit unit : listUnit)
            dlm.addElement(unit);
        jListUnits.setModel(dlm);
        
        //Charge templates
        File file = new File("templates");
        if (file.exists())
        {
            File[] templates = file.listFiles(new FilenameFilter() {

                @Override
                public boolean accept(File file, String name) {
                    if (name.endsWith(".jrxml") && !name.endsWith("answer_subreport.jrxml")) return true; 
                    else 
                        return false;
                }
            });
            
            DefaultComboBoxModel dcm = new DefaultComboBoxModel();
            for (File f : templates)
                dcm.addElement(f.getName());
            jComboBoxTemplates.setModel(dcm);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListUnits = new javax.swing.JList();
        jButtonGenerar = new javax.swing.JButton();
        jTextFieldFileName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerNum = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTemplates = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSubtitle = new javax.swing.JTextField();
        jCheckBoxTheory = new javax.swing.JCheckBox();
        jCheckBoxPractical = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jListUnits);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("testexamgenerator/window/Bundle"); // NOI18N
        jButtonGenerar.setText(bundle.getString("JDialogGenerateExam.jButtonGenerar.text")); // NOI18N
        jButtonGenerar.setToolTipText(bundle.getString("JDialogGenerateExam.jButtonGenerar.toolTipText")); // NOI18N
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jTextFieldFileName.setToolTipText(bundle.getString("JDialogGenerateExam.jTextFieldFileName.toolTipText")); // NOI18N

        jLabel1.setText(bundle.getString("JDialogGenerateExam.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("JDialogGenerateExam.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("JDialogGenerateExam.jLabel3.text")); // NOI18N

        jLabel4.setText(bundle.getString("JDialogGenerateExam.jLabel4.text")); // NOI18N

        jCheckBoxTheory.setSelected(true);
        jCheckBoxTheory.setText(bundle.getString("JDialogGenerateExam.jCheckBoxTheory.text")); // NOI18N

        jCheckBoxPractical.setSelected(true);
        jCheckBoxPractical.setText(bundle.getString("JDialogGenerateExam.jCheckBoxPractical.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTemplates, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxTheory)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxPractical)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxTheory)
                            .addComponent(jCheckBoxPractical))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        if (jListUnits.getSelectedIndices().length<=0)
        {
            JOptionPane.showMessageDialog(this, "Select at least one unit on the left");
            return;
        }
        Integer numQuestions = (Integer)jSpinnerNum.getValue();
        if (numQuestions<=0)
        {
            JOptionPane.showMessageDialog(this,"Question number must be more than 0");
            return;
        }
        String fileName = jTextFieldFileName.getText();
        if ("".equals(fileName))
        {
            JOptionPane.showMessageDialog(this, "You should enter a valid output filename");
            return;
        }
        
        String template = (String)jComboBoxTemplates.getSelectedItem();
        boolean theory = jCheckBoxTheory.isSelected();
        boolean practical = jCheckBoxPractical.isSelected();
        try
        {
            if (BusinessLogic.generateExamenToPdf(numQuestions, jListUnits.getSelectedIndices(), fileName, template,jTextFieldSubtitle.getText(),theory,practical))
                JOptionPane.showMessageDialog(this, "Exam generation OK");
        }
        catch (NotEnoughQuestionsException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JCheckBox jCheckBoxPractical;
    private javax.swing.JCheckBox jCheckBoxTheory;
    private javax.swing.JComboBox jComboBoxTemplates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListUnits;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerNum;
    private javax.swing.JTextField jTextFieldFileName;
    private javax.swing.JTextField jTextFieldSubtitle;
    // End of variables declaration//GEN-END:variables
}
