/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testexamgenerator.window;

import java.lang.reflect.Field;
import javax.swing.DefaultComboBoxModel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author pablo
 */
public class JDialogHtmlEditor extends javax.swing.JDialog {

    private RSyntaxTextArea textArea;
    /**
     * Creates new form JDialogHtmlEditor
     * @param parent
     * @param modal
     * @param initialText
     */
    public JDialogHtmlEditor(java.awt.Frame parent, boolean modal,String initialText) {
        super(parent, modal);
        initComponents();
        

      textArea = new RSyntaxTextArea(20, 60);
      textArea.setCodeFoldingEnabled(true);
      textArea.setText(initialText);
      RTextScrollPane sp = new RTextScrollPane(textArea);
      jPanelEditor.add(sp);
      
      //We load the languages supported for this editor. We have to use reflection... Should be a enum here
      try
      {
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for (Field field : SyntaxConstants.class.getFields())
            dcm.addElement(field.get(null));
        jComboBoxSyntax.setModel(dcm);
        textArea.setSyntaxEditingStyle((String)jComboBoxSyntax.getSelectedItem());
      }
      catch (SecurityException | IllegalArgumentException | IllegalAccessException e)
      {
          //Do nothing in this scenario
      }
      
          
          

      //setContentPane(cp);
      setTitle("Question editor");
      setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanelEditor = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBoxSyntax = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("testexamgenerator/window/Bundle"); // NOI18N
        jButton1.setText(bundle.getString("JDialogHtmlEditor.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelEditor.setLayout(new java.awt.BorderLayout());

        jButton2.setText(bundle.getString("JDialogHtmlEditor.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxSyntax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSyntax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSyntaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxSyntax, 0, 264, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jComboBoxSyntax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ((MainFrame)getParent()).setQuestionText(textArea.getText());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxSyntaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSyntaxActionPerformed
        textArea.setSyntaxEditingStyle((String)jComboBoxSyntax.getSelectedItem());
    }//GEN-LAST:event_jComboBoxSyntaxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxSyntax;
    private javax.swing.JPanel jPanelEditor;
    // End of variables declaration//GEN-END:variables
}
